---

- name: Restart Prometheus container
  docker_container:
    name: "{{ prometheus_container_name }}"
    image: "{{ prometheus_container_image }}"
    state: started
    restart: yes
    published_ports:
      - "{{ prometheus_port }}:{{ prometheus_container_port }}"
    volumes:
      - "{{ prometheus_container_data_volume }}:/prometheus-data"
  register: prometheus_container_result